version: '3.7'
services: 
    backend:
        container_name: backend
        command: poetry run uvicorn src.app:app --host 0.0.0.0 --port 8080
        build: 
            context: ./resume-matching-backend/
            dockerfile: Dockerfile
        restart: always
    nginx:
        container_name: nginx
        build: 
            context: ./resume-matching-frontend/
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
        depends_on: 
            - backend